import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:image_picker/image_picker.dart';
import 'core/providers/gemini_client.dart';
void main()=>runApp(const AiOsApp());
const secureStorage=FlutterSecureStorage();
class AiOsApp extends StatelessWidget{const AiOsApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(title:'AI OS',debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const MainShell());}
class MainShell extends StatefulWidget{const MainShell({super.key});@override State<MainShell> createState()=>_MainShellState();}
class _MainShellState extends State<MainShell>{int index=0;@override Widget build(BuildContext c){final p=[const ChatPage(),const AiRoomPage(),const HistoryPage(),const SettingsPage()];return Scaffold(body:SafeArea(child:IndexedStack(index:index,children:p)),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const[NavigationDestination(icon:Icon(Icons.chat_bubble_outline),label:'채팅'),NavigationDestination(icon:Icon(Icons.hub_outlined),label:'AI 대화방'),NavigationDestination(icon:Icon(Icons.history),label:'기록'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'설정')]));}}
class ChatMessage{ChatMessage(this.text,this.user,{this.attachment});final String text;final bool user;final String? attachment;}
class ChatPage extends StatefulWidget{const ChatPage({super.key});@override State<ChatPage> createState()=>_ChatPageState();}
class _ChatPageState extends State<ChatPage>{final controller=TextEditingController();final messages=<ChatMessage>[];final gemini=const GeminiClient();bool busy=false;String? attachment;
Future<void> attach()async{await showModalBottomSheet<void>(context:context,builder:(ctx)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.camera_alt_outlined),title:const Text('카메라 촬영'),onTap:()async{Navigator.pop(ctx);final x=await ImagePicker().pickImage(source:ImageSource.camera,imageQuality:90);if(x!=null&&mounted)setState(()=>attachment=x.path);}),ListTile(leading:const Icon(Icons.photo_library_outlined),title:const Text('사진 선택'),onTap:()async{Navigator.pop(ctx);final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null&&mounted)setState(()=>attachment=x.path);}),ListTile(leading:const Icon(Icons.folder_open),title:const Text('파일 첨부'),subtitle:const Text('Android 문서 선택기 연동 준비 중'),onTap:()=>Navigator.pop(ctx))])));}
Future<void> send()async{final t=controller.text.trim();if((t.isEmpty&&attachment==null)||busy)return;final a=attachment;setState((){messages.add(ChatMessage(t.isEmpty?'첨부파일 분석':t,true,attachment:a));controller.clear();attachment=null;busy=true;});try{final k=await secureStorage.read(key:'gemini_api_key')??'';if(k.isEmpty)throw Exception('설정에서 Gemini API Key를 먼저 입력하세요.');final ans=await gemini.chat(apiKey:k,prompt:a==null?t:'$t\n\n첨부 이미지: $a');if(mounted)setState(()=>messages.add(ChatMessage(ans,false)));}catch(e){if(mounted)setState(()=>messages.add(ChatMessage('응답 실패\n$e',false)));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Column(children:[const ListTile(title:Text('AI OS',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),subtitle:Text('최상의 결과를 위한 AI 운영체제')),const Divider(height:1),Expanded(child:messages.isEmpty?const Center(child:Text('무엇을 도와드릴까요?')):ListView.builder(itemCount:messages.length,itemBuilder:(_,i){final m=messages[i];return Align(alignment:m.user?Alignment.centerRight:Alignment.centerLeft,child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Text(m.text))));})),if(busy)const LinearProgressIndicator(),SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(8),child:Row(children:[IconButton(onPressed:busy?null:attach,icon:const Icon(Icons.add)),Expanded(child:TextField(controller:controller,minLines:1,maxLines:5,decoration:const InputDecoration(hintText:'메시지를 입력하세요...',border:OutlineInputBorder()))),IconButton(onPressed:busy?null:send,icon:const Icon(Icons.send))])))]);}
class AiRoomPage extends StatelessWidget{const AiRoomPage({super.key});@override Widget build(BuildContext c)=>const EmptyPage(title:'AI 대화방',message:'Planner → Provider → Quality → Result',icon:Icons.hub);}
class HistoryPage extends StatelessWidget{const HistoryPage({super.key});@override Widget build(BuildContext c)=>const EmptyPage(title:'기록',message:'대화 및 결과 기록',icon:Icons.history);}
class SettingsPage extends StatefulWidget{const SettingsPage({super.key});@override State<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{bool freeFirst=true,paid=false;final providers=<String,bool>{'Gemini':true,'Groq':false,'OpenRouter Free':false,'Hugging Face':false,'OpenAI API':false,'Claude API':false};Future<void> keyDialog(String p)async{final key=p=='Gemini'?'gemini_api_key':'${p.toLowerCase().replaceAll(' ','_')}_api_key';final x=TextEditingController(text:await secureStorage.read(key:key)??'');if(!mounted)return;await showDialog<void>(context:context,builder:(d)=>AlertDialog(title:Text('$p API 설정'),content:TextField(controller:x,obscureText:true,decoration:const InputDecoration(labelText:'API Key')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('취소')),FilledButton(onPressed:()async{await secureStorage.write(key:key,value:x.text.trim());if(d.mounted)Navigator.pop(d);},child:const Text('저장'))]));}@override Widget build(BuildContext c)=>ListView(children:[const ListTile(title:Text('설정',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),subtitle:Text('AI 선택 · API · 비용 · 저장공간')),SwitchListTile(value:freeFirst,onChanged:(v)=>setState(()=>freeFirst=v),title:const Text('무료 AI 우선')),SwitchListTile(value:paid,onChanged:(v)=>setState(()=>paid=v),title:const Text('유료 API 사용 허용'),subtitle:const Text('기본 OFF')),const Divider(),...providers.entries.map((e)=>Card(child:Column(children:[SwitchListTile(value:e.value,onChanged:(v)=>setState(()=>providers[e.key]=v),title:Text(e.key)),TextButton.icon(onPressed:()=>keyDialog(e.key),icon:const Icon(Icons.key),label:const Text('API 설정'))]))),const ListTile(title:Text('AI OS'),subtitle:Text('Version 0.2.0\nCreator: Daehyun Kang'))]);}
class EmptyPage extends StatelessWidget{const EmptyPage({required this.title,required this.message,required this.icon,super.key});final String title,message;final IconData icon;@override Widget build(BuildContext c)=>Column(children:[ListTile(title:Text(title,style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold))),Expanded(child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:52),const SizedBox(height:16),Text(message)]))) ]);}
